version: '3.8'

services:
  virtual-finland-demo:
    # build:
    # context: .
    # dockerfile: Dockerfile
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 3004:3000
    # environment:
    # - CHOKIDAR_USEPOLLING=true
    # - WATCHPACK_POLLING=true
    networks:
      - vfd-network
    labels:
      - traefik.http.routers.virtual-finland-demo.rule=Host(`virtual-finland-demo.localhost`)
    environment:
      - NEXT_PUBLIC_APP_BASE_URL=http://virtual-finland-demo.localhost

networks:
  vfd-network:
    external: true
    driver: bridge
